site_name: TiLearn
site_url: https://bancie.github.io/TiLearn/
site_author: Bancie
repo_url: https://github.com/Bancie/TiLearn
repo_name: Bancie/TiLearn

nav:
  - Home: index.md
  - Getting started: getting-started/index.md
  - User Guide:
    - user-guide/index.md
    #- Single Machine:
    - Maximum Lateness: user-guide/single-machine/lateness/edd.md
    - Total Completion Time: user-guide/single-machine/completion/wspt.md
      #- Sequence jobs: user-guide/single-machine/completion/sequence.md
      #- Release jobs: user-guide/single-machine/completion/release.md
  #- Building from source: run/index.md
  - API reference:
    - api-reference/index.md
    - tilearn.show_mytime: api-reference/in-job/i-job.md
  - News: news/index.md
  - About: about.md

plugins:
    - social:
    #- glightbox
    - search: {}
    - encryptcontent:
        title_prefix: ''
        summary: 'A password is required to access this page.'
        placeholder: 'Please enter your password.'
        decryption_failure_message: 'Try again!'
        encryption_info_message: "Please enter your password below."
        input_class: 'md-search__form md-search__input'
        button_class: 'md-search__icon'


theme:
  name: material
  features:
     - toc.follow
     - navigation.footer
     - navigation.tabs
     - navigation.tabs.sticky
     - navigation.expand
     - navigation.path
     - navigation.indexes
     - navigation.instant.preview
     - navigation.sections
     - navigation.top
     - search.suggest
     - search.highlight
     - content.tabs.link
     - content.code.annotation
     - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
      primary: indigo
      accent: yellow
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: yellow 
  font:
    text: Source Code Pro
  logo: tilearn2.png
  favicon: tilearn.png
  icon:
    repo: fontawesome/brands/github
    logo: logo
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
  - css/extra.css

copyright: |
  &copy; 2024 <a href="https://web.facebook.com/ngchibangg"  target="_blank" rel="noopener">Bancie Nguyen</a>

extra:
  homepage: https://bancie.github.io/TiLearn/
  social:
    - icon: fontawesome/brands/facebook
      link: https://web.facebook.com/ngchibangg
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bancie.007/
    - icon: fontawesome/brands/github
      link: https://github.com/Bancie